/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as GoodiesRouteImport } from './routes/goodies'
import { Route as CraftsRouteImport } from './routes/crafts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works.index'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodiesRoute = GoodiesRouteImport.update({
  id: '/goodies',
  path: '/goodies',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsRoute = CraftsRouteImport.update({
  id: '/crafts',
  path: '/crafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/crafts': typeof CraftsRoute
  '/goodies': typeof GoodiesRoute
  '/journeys': typeof JourneysRoute
  '/stories': typeof StoriesRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/crafts': typeof CraftsRoute
  '/goodies': typeof GoodiesRoute
  '/journeys': typeof JourneysRoute
  '/stories': typeof StoriesRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/crafts': typeof CraftsRoute
  '/goodies': typeof GoodiesRoute
  '/journeys': typeof JourneysRoute
  '/stories': typeof StoriesRoute
  '/works/$slug': typeof WorksSlugRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/crafts'
    | '/goodies'
    | '/journeys'
    | '/stories'
    | '/works/$slug'
    | '/works'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/crafts'
    | '/goodies'
    | '/journeys'
    | '/stories'
    | '/works/$slug'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/crafts'
    | '/goodies'
    | '/journeys'
    | '/stories'
    | '/works/$slug'
    | '/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CraftsRoute: typeof CraftsRoute
  GoodiesRoute: typeof GoodiesRoute
  JourneysRoute: typeof JourneysRoute
  StoriesRoute: typeof StoriesRoute
  WorksSlugRoute: typeof WorksSlugRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodies': {
      id: '/goodies'
      path: '/goodies'
      fullPath: '/goodies'
      preLoaderRoute: typeof GoodiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts': {
      id: '/crafts'
      path: '/crafts'
      fullPath: '/crafts'
      preLoaderRoute: typeof CraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CraftsRoute: CraftsRoute,
  GoodiesRoute: GoodiesRoute,
  JourneysRoute: JourneysRoute,
  StoriesRoute: StoriesRoute,
  WorksSlugRoute: WorksSlugRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
